version: "3.8"

services:
  # Flask application container
  flask_app:
    build: ./flask_app
    container_name: flask_app
    expose:
      - "5000"
    environment:
      - VIRTUAL_HOST=zemlya.shop,www.zemlya.shop
      - LETSENCRYPT_HOST=zemlya.shop,www.zemlya.shop
      - LETSENCRYPT_EMAIL=jabulani9955@gmail.com
    volumes:
      - /home/jabun/code/torgi_app/data/maps:/app/templates/maps
    networks:
      - webproxy

  # Nginx proxy container
  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - webproxy
    restart: unless-stopped

  # Let's Encrypt companion container for automatic HTTPS certificates
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_letsencrypt
    environment:
      NGINX_PROXY_CONTAINER: nginx_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:rw
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - nginx_proxy
    networks:
      - webproxy
    restart: unless-stopped

networks:
  webproxy:
    driver: bridge
